version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build: 
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - db
    image: php:8.2-apache
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8080:80
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password_here  # เปลี่ยนเป็นรหัสผ่าน root ของ MySQL
      MYSQL_DATABASE: your_database_name_here  # เปลี่ยนเป็นชื่อฐานข้อมูลที่คุณต้องการ
      MYSQL_USER: your_mysql_user_here  # เปลี่ยนเป็นชื่อผู้ใช้ MySQL
      MYSQL_PASSWORD: your_mysql_password_here  # เปลี่ยนเป็นรหัสผ่านของผู้ใช้ MySQL
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
